fix(marketing): disable contentful client when no secrets are present
The contentful client throws an error if the required secrets are not present.

Unfortunately, this results in Next.js crashing with the following error during a build:

```
   Collecting page data  ..Error: Failed to collect configuration for /[locale]/[slug]
    at <unknown> (/workspaces/code-dot-org/frontend/node_modules/next/dist/build/utils.js:1131:23)
    at async Span.traceAsyncFn (/workspaces/code-dot-org/frontend/node_modules/next/dist/trace/trace.js:153:20) {
  [cause]: TypeError: Expected parameter accessToken
      at <unknown> (/workspaces/code-dot-org/frontend/apps/marketing/.next/server/app/[locale]/[slug]/page.js:7:4934)
      at 66569 (/workspaces/code-dot-org/frontend/apps/marketing/.next/server/app/[locale]/[slug]/page.js:7:9138)
      at Function.t (/workspaces/code-dot-org/frontend/apps/marketing/.next/server/webpack-runtime.js:1:128)
      at async getLayoutOrPageModule (/workspaces/code-dot-org/frontend/node_modules/next/dist/server/lib/app-dir-module.js:37:15)
      at async collectAppPageSegments (/workspaces/code-dot-org/frontend/node_modules/next/dist/build/segment-config/app/app-segments.js:50:45)
      at async (/workspaces/code-dot-org/frontend/node_modules/next/dist/build/utils.js:1129:28)
      at async Span.traceAsyncFn (/workspaces/code-dot-org/frontend/node_modules/next/dist/trace/trace.js:153:20)
}

> Build error occurred
Error: Failed to collect page data for /[locale]/[slug]
    at <unknown> (/workspaces/code-dot-org/frontend/node_modules/next/dist/build/utils.js:1234:15) {
  type: 'Error'
```

Rather than crashing the build, the client should be `undefined` when the required secrets are not present.
If the client is `undefined`, the page will not render any content from Contentful, allowing Next.js to produce foundational static pages that it can pre-render.